name: Remove Pull Request Images When PR is Closed
permissions: read-all
on:
  pull_request:
    types: [closed]
jobs:
  delete-pr-image:
    name: Delete PR image after PR was closed
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Delete PR image
        uses: dataaxiom/ghcr-cleanup-action@d52806a0dc70b430571a37da1fde39733ffd640f # v1
        with:
          delete-tags: pr-${{github.event.pull_request.number}}
