name: Remove Pull Request Images When PR is Closed
permissions: read-all
on:
  pull_request:
    types: [closed]
jobs:
  delete-pr-image:
    name: Delete PR image after PR was closed
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Delete PR image
        uses: dataaxiom/ghcr-cleanup-action@d52806a0dc70b430571a37da1fde39733ffd640f # v1
        with:
          delete-tags: pr-${{github.event.pull_request.number}}
