name: Remove Pull Request Images When PR is Closed
permissions: read-all
on:
  pull_request:
    types: [closed]
jobs:
  delete-pr-image:
    name: Delete PR image after PR was closed
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Delete PR image
        uses: dataaxiom/ghcr-cleanup-action@d52806a0dc70b430571a37da1fde39733ffd640f # v1
        with:
          delete-tags: pr-${{github.event.pull_request.number}}
